# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 404notfound129
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: science-project
# "service" is the name of this project. This will also be added to your AWS resource names.
service: science-project-2025

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: ["provided.al2023"] # the plugin compiles a function only if runtime is declared here (either on function or provider level)
    buildProvidedRuntimeAsBootstrap: true # if enabled, builds and archive function with only single "bootstrap" binary (useful for runtimes like provided.al2)

provider:
  name: aws
  httpApi:
    cors:  true

functions:
  calc-python:
    runtime: python3.12
    handler: handler.hello
    events:
      - httpApi:
          path: /calc/python
          method: post
  calc-go:
    runtime: provided.al2023
    handler: handler.go
    events:
      - httpApi:
          path: /calc/go
          method: post
